using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Gabystation.ServerCurrency.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GamblingWindow : DefaultWindow
    {
        public GamblingWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }
    }
}
