using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ResourceManagement;
using Content.Client._durkcode.ServerCurrency;

namespace Content.Client._Gabystation.ServerCurrency.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GamblingWindow : DefaultWindow
    {

        [Dependency] private readonly ServerCurrencySystem _serverCur = default!;
        [Dependency] private readonly IResourceCache _resCache = default!;

        public GamblingStates currentState = GamblingStates.Lobby;
        public event Action<int, string>? OnPlay;

        private readonly string[] gameModes = ["Double"]; // This is the only game mode at the moment
        private string gameOption = "";
        private string selectedGame = "Double";

        public GamblingWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            for (int i = 0; i < gameModes.Length; i++) //TODO: Support to more gamemodes (will need a prototype)
            {
                LobbyGameMode.AddItem(gameModes[i], 0);
            }
            LobbyGameOption.AddItem("Red (2x)", 0);

            _serverCur.BalanceChange += UpdatePlayerBalance;

            LobbyPlayButton.OnPressed += _ => SetupPlayState();
            ResultRestartButton.OnPressed += _ => SetupLobbyState();

            UpdateGamePreview();
        }

        public void UpdatePlayerBalance()
        {
            var balance = _serverCur.GetBalance();
            FooterCurrency.Text = _serverCur.Stringify(balance);
        }

        public void SetupPlayState()
        {
            if (currentState == GamblingStates.Game)
                return;

            if (!int.TryParse(LobbyMoneyDeposit.Text, out var value) || value <= 0 || !_serverCur.CanAfford(value, out _))
                return;

            Lobby.Visible = false;
            Game.Visible = true;
            Result.Visible = false;
            ResultLabel.Text = "";
            currentState = GamblingStates.Game;
            OnPlay?.Invoke(value, "Red");
        }

        public void SetupLobbyState()
        {
            if (currentState == GamblingStates.Lobby)
                return;

            Lobby.Visible = true;
            Game.Visible = false;
            LobbyMoneyDeposit.Text = "0";
            gameOption = "";
            currentState = GamblingStates.Lobby;
        }

        public void ShowResult(bool won)
        {
            Result.Visible = true;
            ResultLabel.Text = won ? "[color=green]You won!" : "[color=red]You lose!";
        }

        public void UpdateGamePreview()
        {
            var selectedTexture = _resCache.GetResource<TextureResource>($"/Textures/_Gabystation/Textures/Gambling/{selectedGame}.png");
            SelectedGameTexture.Texture = selectedTexture;
        }
    }

    public enum GamblingStates
    {
        Lobby = 0,
        Game = 1
    }
}
