using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ResourceManagement;
using Content.Client._durkcode.ServerCurrency;
using Robust.Shared.Random;
using Robust.Shared.Timing;

namespace Content.Client._Gabystation.ServerCurrency.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GamblingWindow : DefaultWindow
    {

        [Dependency] private readonly ServerCurrencySystem _serverCur = default!;
        [Dependency] private readonly IResourceCache _resCache = default!;

        public GamblingStates CurrentState = GamblingStates.Lobby;
        public event Action<int, string>? OnPlay;

        private readonly string[] gameModes = ["Double"]; // This is the only game mode at the moment
        private string gameOption = "";
        private string selectedGame = "Double";
        private bool playingAnim = false;

        public GamblingWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            for (int i = 0; i < gameModes.Length; i++) //TODO: Support to more gamemodes (will need a prototype)
            {
                LobbyGameMode.AddItem(gameModes[i], 0);
            }
            LobbyGameOption.AddItem("Red (2x)", 0);
            LobbyGameOption.AddItem("Black (2x)", 0);
            LobbyGameOption.AddItem("White (10x)", 0);

            _serverCur.BalanceChange += UpdatePlayerBalance;

            LobbyPlayButton.OnPressed += _ => SetupPlayState();
            ResultRestartButton.OnPressed += _ => HandleRestartButton();

            UpdateGamePreview();
        }

        public void UpdatePlayerBalance()
        {
            var balance = _serverCur.GetBalance();
            FooterCurrency.Text = _serverCur.Stringify(balance);
        }

        public void SetupPlayState()
        {
            if (!int.TryParse(LobbyMoneyDeposit.Text, out var value) || value <= 0)
                return;

            // Get selected option
            gameOption = LobbyGameOption.SelectedId switch
            {
                0 => "Red",
                1 => "Black",
                2 => "White",
                _ => "Red"
            };

            Lobby.Visible = false;
            Game.Visible = true;
            Result.Visible = false;
            ResultLabel.Text = "";
            CurrentState = GamblingStates.Game;

            // Começa animação antes de enviar para o servidor
            StartRollAnimation(gameOption, () =>
            {
                // Depois que a animação termina, envia pro servidor
                OnPlay?.Invoke(value, gameOption);
            });
        }

        public void SetupLobbyState()
        {
            if (CurrentState == GamblingStates.Lobby)
                return;

            Lobby.Visible = true;
            Game.Visible = false;
            playingAnim = false;
            //LobbyMoneyDeposit.Text = "0";
            gameOption = "";
            CurrentState = GamblingStates.Lobby;
        }

        public void ShowResult(bool won)
        {
            Result.Visible = true;
            ResultLabel.Text = won ? "[color=green]You won!" : "[color=red]You lose!";
        }

        public void UpdateGamePreview()
        {
            var selectedTexture = _resCache.GetResource<TextureResource>($"/Textures/_Gabystation/Textures/Gambling/{selectedGame}.png");
            SelectedGameTexture.Texture = selectedTexture;
        }

        private void HandleRestartButton()
        {
            if (CurrentState != GamblingStates.Game || !Result.Visible)
                return;

            SetupLobbyState();
        }

        public void StartRollAnimation(string selectedOption, Action onFinished)
        {
            // Inicia efeito visual (loop de 3 quadrados mudando de cor aleatória)
            playingAnim = true;

            var random = IoCManager.Resolve<IRobustRandom>();
            var availableColors = new[] { "Red", "Black", "White" };

            var ticks = 0;
            var maxTicks = 30;
            var timer = new Timer(100, true); // 100ms por tick

            timer.OnTick += _ =>
            {
                ticks++;

                // Muda as cores aleatoriamente nos quadrados
                for (int i = 0; i < 3; i++)
                {
                    var color = availableColors[random.Next(availableColors.Length)];
                    SetBoxColor(i, color);
                }

                if (ticks >= maxTicks)
                {
                    timer.Stop();
                    playingAnim = false;

                    // Terminou animação → avisa servidor
                    onFinished.Invoke();
                }
            };

            timer.Start();
        }

    }

    public enum GamblingStates
    {
        Lobby = 0,
        Game = 1
    }
}
