using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client._Starfall.UserInterface.Controls; // _Starfall New WordWrapHelper
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._UM.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class FancySpeechBubble : Control
{
    public int WordWrapLength = 32;

    private int _fontSize;
    private string _font;
    private Color? _color;
    private bool _forceFont;
    private int? _thicknessOverride;
    private string? _contentTag;
    private string? _glyph;

    public FancySpeechBubble(ChatMessage message, int fontSize = 12, string font = "Minecraft", bool forceFont = false, Color? fontColor = null, int? thicknessOverride = null, string? contentTag = null, string? glyph = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _color = fontColor;
        _fontSize = fontSize;
        _font = font;
        _forceFont = forceFont;
        _thicknessOverride = thicknessOverride;
        _contentTag = contentTag;
        _glyph = glyph;

        BuildLines(message, _contentTag);
    }

    // _Starfall Start
    // Static regex to match the font tag in the message without reparsing regex everytime
    private static readonly Regex FontRegex = new(
        @"\[font=([^\s\]]+)\s+size=(\d+)\]",
        RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>
    /// Gets the font that the message has.
    /// </summary>
    /// <param name="message"></param>
    private (string? FontName, int? FontSize) ParseFont(string input)
    {
        var match = FontRegex.Match(input); // _Starfall: Use the static regex to match the font tag in the message without reparsing regex everytime

        if (match.Success)
        {
            string fontName = match.Groups[1].Value;
            int fontSize = int.Parse(match.Groups[2].Value);
            return (fontName, fontSize);
        }
        return (null, null);
    }

    // _Starfall Start
    private void BuildLines(ChatMessage chatMessage, string? tag)
    {
        // _Starfall: Get the message string inside the tag if it exists, otherwise use the wrapped message
        var messageString = tag != null
            ? SharedChatSystem.GetStringInsideTag(chatMessage, tag)
            : chatMessage.WrappedMessage;

        // _Starfall Start
        // Skip font parsing if the font is forced
        if (!_forceFont)
        {
            var font = ParseFont(chatMessage.WrappedMessage);

            if (font.FontName != null)
                _font = font.FontName;

            if (font.FontSize != null)
                _fontSize = font.FontSize.Value;
        }
        // _Starfall end

        var wraptest = WordWrapHelper.WordWrap(messageString, WordWrapLength);

        // Holds all wrapped text lines
        var textContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Align = BoxContainer.AlignMode.Center,
        };

        // _Starfall: Create a dictionary to hold the font parameters for the markup node
        var fontParameters = new Dictionary<string, MarkupParameter>
        {
            ["size"] = new MarkupParameter(_fontSize)
        };

        foreach (var message in wraptest)
        {
            // Log.Debug("message: " + message); // _Starfall: we dont need to log speech bubbles

            var msg = new FormattedMessage();

            // _Starfall: Push the font tag with the font parameters to the message instead of recreating font parameters for every line
            msg.PushTag(new MarkupNode(
                "font",
                new MarkupParameter(_font),
                fontParameters));
            
            var cleanMessage = System.Text.RegularExpressions.Regex.Replace(message, @"\[/?color[^\]]*\]", "", System.Text.RegularExpressions.RegexOptions.IgnoreCase);

            if (_color != null)
                msg.PushColor(_color.Value);

            msg.AddMarkupOrThrow(cleanMessage);
            msg.Pop();
            msg.Pop();

            var thickness = _fontSize / 6;

            if (_thicknessOverride != null)
                thickness = _thicknessOverride.Value;

            var label = new OutlineRichTextLabel
            {
                Thickness = thickness,
                StyleClasses = { "bubbleContent" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(thickness * 3),
            };

            label.SetMessage(msg,
                tagsAllowed: [ typeof(FontTag), typeof(ColorTag), typeof(BoldTag) ]);

            textContainer.AddChild(label);
        }

        // Root container that holds icon + text
        var labelContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Align = BoxContainer.AlignMode.Center,
            SeparationOverride = 6,
        };

        if (_glyph != null)
        {
            var textureRect = new TextureRect
            {
                TexturePath = _glyph,
                TextureScale = new Vector2(2, 2),
                Stretch = TextureRect.StretchMode.KeepCentered,
                VerticalAlignment = VAlignment.Center,
            };

            labelContainer.AddChild(textureRect);
        }

        labelContainer.AddChild(textContainer);

        TextContainer.AddChild(labelContainer);
    }
    // _Starfall End

    /// <summary>
    /// Where the barely working magic happens
    /// </summary>
    /// <param name="message"></param>
    /// <returns></returns>
    // private List<FormattedMessage> BuildMessages(FormattedMessage message)
    // {
    //   _Starfall Here lies where the barely working magic happens because i made the magic work better
    // }

}

